

# Control
NETWORK_INTERFACE = "enp0s31f6"
CONTROL_DT = 1. / 250.

# XR
XR_CONTROLLER_TRIGGER_THRESHOLD = 0.5

# Robot
G1_ARM_SDK_WEIGHT_MOTOR_IDX = 29
WALKING_SPEED_FORWARD = 0.5
WALKING_SPEED_STRAFE = 0.0
WALKING_SPEED_THETA = 0.7
